version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566" # Porta para SQS
      - "4571:4571" # Porta para o painel de controle da Web
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
